## Question 1

In [1]:
import pandas as pd
df=pd.read_csv('house_prices.csv')

In [2]:
df.head(5)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

## Question 2

In [3]:
#Replace all column values which contain ‘?’ and 'n.a' and 'null' with NaN (Hint :use the read_csv argument called na_values)
hp_df=pd.read_csv('house_prices.csv', na_values=['?','n.a','null'])
hp_df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

## Question 3

In [4]:
#Print out the first 20 rows
df.head(20)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0    1          60       RL         65.0     8450   Pave   NaN      Reg   
1    2          20       RL         80.0     9600   Pave   NaN      Reg   
2    3          60       RL         68.0    11250   Pave   NaN      IR1   
3    4          70       RL         60.0     9550   Pave   NaN      IR1   
4    5          60       RL         84.0    14260   Pave   NaN      IR1   
5    6          50       RL         85.0    14115   Pave   NaN      IR1   
6    7          20       RL         75.0    10084   Pave   NaN      Reg   
7    8          60       RL          NaN    10382   Pave   NaN      IR1   
8    9          50       RM         51.0     6120   Pave   NaN      Reg   
9   10         190       RL         50.0     7420   Pave   NaN      Reg   
10  11          20       RL         70.0    11200   Pave   NaN      Reg   
11  12          60       RL         85.0    11924   Pave   NaN      IR1   
12  13          20       RL          NaN    12968   Pave   NaN      IR2   
13  14          20       RL         91.0    10652   Pave   NaN      IR1   
14  15          20       RL          NaN    10920   Pave   NaN      IR1   
15  16          45       RM         51.0     6120   Pave   NaN      Reg   
16  17          20       RL          NaN    11241   Pave   NaN      IR1   
17  18          90       RL         72.0    10791   Pave   NaN      Reg   
18  19          20       RL         66.0    13695   Pave   NaN      Reg   
19  20          20       RL         70.0     7560   Pave   NaN      Reg   

   LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0          Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1          Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2          Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3          Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4          Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
5          Lvl    AllPub  ...        0    NaN  MnPrv        Shed     700   
6          Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
7          Lvl    AllPub  ...        0    NaN    NaN        Shed     350   
8          Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
9          Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
10         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
11         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
12         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
13         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
14         Lvl    AllPub  ...        0    NaN   GdWo         NaN       0   
15         Lvl    AllPub  ...        0    NaN  GdPrv         NaN       0   
16         Lvl    AllPub  ...        0    NaN    NaN        Shed     700   
17         Lvl    AllPub  ...        0    NaN    NaN        Shed     500   
18         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
19         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   

   MoSold YrSold  SaleType  SaleCondition  SalePrice  
0       2   2008        WD         Normal     208500  
1       5   2007        WD         Normal     181500  
2       9   2008        WD         Normal     223500  
3       2   2006        WD        Abnorml     140000  
4      12   2008        WD         Normal     250000  
5      10   2009        WD         Normal     143000  
6       8   2007        WD         Normal     307000  
7      11   2009        WD         Normal     200000  
8       4   2008        WD        Abnorml     129900  
9       1   2008        WD         Normal     118000  
10      2   2008        WD         Normal     129500  
11      7   2006       New        Partial     345000  
12      9   2008        WD         Normal     144000  
13      8   2007       New        Partial     279500  
14    

## Question 4

In [5]:
#Print out the last 20 rows
hp_df.tail(20)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
1440  1441          70       RL         79.0    11526   Pave   NaN      IR1   
1441  1442         120       RM          NaN     4426   Pave   NaN      Reg   
1442  1443          60       FV         85.0    11003   Pave   NaN      Reg   
1443  1444          30       RL          NaN     8854   Pave   NaN      Reg   
1444  1445          20       RL         63.0     8500   Pave   NaN      Reg   
1445  1446          85       RL         70.0     8400   Pave   NaN      Reg   
1446  1447          20       RL          NaN    26142   Pave   NaN      IR1   
1447  1448          60       RL         80.0    10000   Pave   NaN      Reg   
1448  1449          50       RL         70.0    11767   Pave   NaN      Reg   
1449  1450         180       RM         21.0     1533   Pave   NaN      Reg   
1450  1451          90       RL         60.0     9000   Pave   NaN      Reg   
1451  1452          20       RL         78.0     9262   Pave   NaN      Reg   
1452  1453         180       RM         35.0     3675   Pave   NaN      Reg   
1453  1454          20       RL         90.0    17217   Pave   NaN      Reg   
1454  1455          20       FV         62.0     7500   Pave  Pave      Reg   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
1440         Bnk    AllPub  ...        0    NaN    NaN         NaN       0   
1441         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1442         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1443         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1444         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1445         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1446         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1447         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1448         Lvl    AllPub  ...        0    NaN   GdWo         NaN       0   
1449         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1450         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1451         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1452         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1453         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1454         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
1440      9   2008        WD         Normal     191000  
1441      5   2008        WD         Normal     149300  
1442      4   2009        WD         Normal     310000  
1443      5   2009        WD         Normal     121000  
1444     11   2007        WD         Normal     179600  
1445      5   2007        WD         Normal     129000  
1446      4   2010        WD         Normal     157900  
1447     12   2007        WD         Normal     240000  
1448      5   2007        WD         Normal     112000  
1449      8   2006        WD        Abnorml      92000  
1450      9   2009        WD         Normal     136000  
1451      5   2009       

## Question 5 Print out the first and last 20 rows as one datafame.(Hint use pandas concat function)

In [6]:

first=hp_df.head(20)
last=hp_df.tail(20)
pd.concat([first,last],axis=1,)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0      1.0        60.0       RL         65.0   8450.0   Pave   NaN      Reg   
1      2.0        20.0       RL         80.0   9600.0   Pave   NaN      Reg   
2      3.0        60.0       RL         68.0  11250.0   Pave   NaN      IR1   
3      4.0        70.0       RL         60.0   9550.0   Pave   NaN      IR1   
4      5.0        60.0       RL         84.0  14260.0   Pave   NaN      IR1   
5      6.0        50.0       RL         85.0  14115.0   Pave   NaN      IR1   
6      7.0        20.0       RL         75.0  10084.0   Pave   NaN      Reg   
7      8.0        60.0       RL          NaN  10382.0   Pave   NaN      IR1   
8      9.0        50.0       RM         51.0   6120.0   Pave   NaN      Reg   
9     10.0       190.0       RL         50.0   7420.0   Pave   NaN      Reg   
10    11.0        20.0       RL         70.0  11200.0   Pave   NaN      Reg   
11    12.0        60.0       RL         85.0  11924.0   Pave   NaN      IR1   
12    13.0        20.0       RL          NaN  12968.0   Pave   NaN      IR2   
13    14.0        20.0       RL         91.0  10652.0   Pave   NaN      IR1   
14    15.0        20.0       RL          NaN  10920.0   Pave   NaN      IR1   
15    16.0        45.0       RM         51.0   6120.0   Pave   NaN      Reg   
16    17.0        20.0       RL          NaN  11241.0   Pave   NaN      IR1   
17    18.0        90.0       RL         72.0  10791.0   Pave   NaN      Reg   
18    19.0        20.0       RL         66.0  13695.0   Pave   NaN      Reg   
19    20.0        20.0       RL         70.0   7560.0   Pave   NaN      Reg   
1440   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1441   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1442   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1443   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1444   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1445   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1446   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1447   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1448   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1449   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1450   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1451   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1452   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1453   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1454   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1455   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1456   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1457   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1458   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   
1459   NaN         NaN      NaN          NaN      NaN    NaN   NaN      NaN   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...      NaN    NaN    NaN         NaN     NaN   
1            Lvl    AllPub  ...      NaN    NaN    NaN         NaN     NaN   
2            Lvl    AllPub  ...      NaN    NaN    NaN         NaN     NaN   
3            Lvl    AllPub  ...      NaN    NaN    NaN         NaN     NaN   
4            Lvl    AllPub  ...      NaN    NaN    NaN         NaN     NaN   
5            Lvl    AllPub  ...      NaN    NaN    NaN         NaN     NaN   
6            Lvl    AllPub  ...      NaN    NaN    NaN         NaN     NaN   
7            Lvl    AllPub  ...      NaN    NaN    NaN         NaN     NaN   
8            Lvl    AllPub  ...      NaN    NaN    NaN         NaN

## Question 6  Print out the columns, shape and information about the dataset.


In [7]:
hp_df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [8]:
hp_df.shape


(1460, 81)

In [9]:
hp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-n

## Question 7

In [10]:
#State how many rows and columns the dataset has; in addition to this, how many int, float and object variables are present.
hp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-n

In [11]:
len(hp_df.index)

1460

In [12]:
len(hp_df.columns)

81

## Question 8

In [13]:
#Rename column ‘BldgType’ to BuildingType, ‘RoofMatl’ to RoofMaterial, ‘MoSold’ to MonthSold and ‘YrSold’ to YearSold.
df.rename(columns={'BldgType':'BuildingType','RoofMatl':'RoofMaterial','MoSold':'MonthSold','YrSold':'YearSold'},inplace=True)
df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MonthSold YearSold  SaleType  SaleCondition  SalePrice  
0            2     2008        WD         Normal     208500  
1            5     2007        WD         Normal     181500  
2            9     2008        WD         Normal     223500  
3            2     2006        WD        Abnorml     140000  
4           12     2008        WD         Normal     250000  
...        ...      ...       ...            ...        ...  
1455         8     2007        WD         Normal     175000  
1456         2     2010        WD         Normal     210000  
1457         5     2010        WD         Normal     266500  
1458         4     2010        WD         Normal     142125  
1459         6     2008        WD         Normal     147500  

[1460 rows x 81 columns]

## Question 9

In [61]:
#Get the Summary Statistics of the DataSet and Explain them
df.describe(include=object)

MSZoning Street Alley LotShape LandContour Utilities LotConfig  \
count      1460   1460    91     1460        1460      1460      1460   
unique        5      2     2        4           4         2         5   
top          RL   Pave  Grvl      Reg         Lvl    AllPub    Inside   
freq       1151   1454    50      925        1311      1459      1052   

       LandSlope Neighborhood Condition1  ... GarageType GarageFinish  \
count       1460         1460       1460  ...       1379         1379   
unique         3           25          9  ...          6            3   
top          Gtl        NAmes       Norm  ...     Attchd          Unf   
freq        1382          225       1260  ...        870          605   

       GarageQual GarageCond PavedDrive PoolQC  Fence MiscFeature SaleType  \
count        1379       1379       1460      7    281          54     1460   
unique          5          5          3      3      4           4        9   
top            TA         TA          Y     Gd  MnPrv        Shed       WD   
freq         1311       1326       1340      3    157          49     1267   

       SaleCondition  
count           1460  
unique             6  
top           Normal  
freq            1198  

[4 rows x 43 columns]

## Question 10

In [66]:
#In your opinion, does the dataset require cleaning?(Check for missing values and Duplicates)
hp_df.duplicated()

Id
1       False
2       False
3       False
4       False
5       False
        ...  
1456    False
1457    False
1458    False
1459    False
1460    False
Length: 1460, dtype: bool

In [68]:
#Yes our dataset requires cleaning
df.isnull()

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
0     False       False     False        False    False   False   True   
1     False       False     False        False    False   False   True   
2     False       False     False        False    False   False   True   
3     False       False     False        False    False   False   True   
4     False       False     False        False    False   False   True   
...     ...         ...       ...          ...      ...     ...    ...   
1455  False       False     False        False    False   False   True   
1456  False       False     False        False    False   False   True   
1457  False       False     False        False    False   False   True   
1458  False       False     False        False    False   False   True   
1459  False       False     False        False    False   False   True   

      LotShape  LandContour  Utilities  ...  PoolQC  Fence  MiscFeature  \
0        False        False      False  ...    True   True         True   
1        False        False      False  ...    True   True         True   
2        False        False      False  ...    True   True         True   
3        False        False      False  ...    True   True         True   
4        False        False      False  ...    True   True         True   
...        ...          ...        ...  ...     ...    ...          ...   
1455     False        False      False  ...    True   True         True   
1456     False        False      False  ...    True  False         True   
1457     False        False      False  ...    True  False        False   
1458     False        False      False  ...    True   True         True   
1459     False        False      False  ...    True   True         True   

      MiscVal  MonthSold  YearSold  SaleType  SaleCondition  SalePrice  \
0       False      False     False     False          False      False   
1       False      False     False     False          False      False   
2       False      False     False     False          False      False   
3       False      False     False     False          False      False   
4       False      False     False     False          False      False   
...       ...        ...       ...       ...            ...        ...   
1455    False      False     False     False          False      False   
1456    False      False     False     False          False      False   
1457    False      False     False     False          False      False   
1458    False      False     False     False          False      False   
1459    False      False     False     False          False      False   

      LotArea sqm  
0           False  
1           False  
2           False  
3           False  
4           False  
...           ...  
1455        False  
1456        False  
1457        False  
1458        False  
1459        False  

[1460 rows x 82 columns]

## Question 11

In [16]:
#How many missing values do we have on each column?

In [70]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
YearSold           0
SaleType           0
SaleCondition      0
SalePrice          0
LotArea sqm        0
Length: 82, dtype: int64

## Question 12

In [72]:
#Try calculating the percentage of missing values on each column(Hint :total_missing_values/total length of dataframe * 100)

total_missing_values = df.isnull().sum() * 100 / len(df)
total_missing_values

Id                0.000000
MSSubClass        0.000000
MSZoning          0.000000
LotFrontage      17.739726
LotArea           0.000000
                   ...    
YearSold          0.000000
SaleType          0.000000
SaleCondition     0.000000
SalePrice         0.000000
LotArea sqm       0.000000
Length: 82, dtype: float64

## Question 13

In [17]:
#Drop Column Alley
hp_df.drop(['Alley'],axis=1, inplace=True)
hp_df


Id  MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  \
0        1          60       RL         65.0     8450   Pave      Reg   
1        2          20       RL         80.0     9600   Pave      Reg   
2        3          60       RL         68.0    11250   Pave      IR1   
3        4          70       RL         60.0     9550   Pave      IR1   
4        5          60       RL         84.0    14260   Pave      IR1   
...    ...         ...      ...          ...      ...    ...      ...   
1455  1456          60       RL         62.0     7917   Pave      Reg   
1456  1457          20       RL         85.0    13175   Pave      Reg   
1457  1458          70       RL         66.0     9042   Pave      Reg   
1458  1459          20       RL         68.0     9717   Pave      Reg   
1459  1460          20       RL         75.0     9937   Pave      Reg   

     LandContour Utilities LotConfig  ... PoolArea PoolQC  Fence MiscFeature  \
0            Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
1            Lvl    AllPub       FR2  ...        0    NaN    NaN         NaN   
2            Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
3            Lvl    AllPub    Corner  ...        0    NaN    NaN         NaN   
4            Lvl    AllPub       FR2  ...        0    NaN    NaN         NaN   
...          ...       ...       ...  ...      ...    ...    ...         ...   
1455         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
1456         Lvl    AllPub    Inside  ...        0    NaN  MnPrv         NaN   
1457         Lvl    AllPub    Inside  ...        0    NaN  GdPrv        Shed   
1458         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
1459         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   

     MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0          0      2    2008        WD         Normal     208500  
1          0      5    2007        WD         Normal     181500  
2          0      9    2008        WD         Normal     223500  
3          0      2    2006        WD        Abnorml     140000  
4          0     12    2008        WD         Normal     250000  
...      ...    ...     ...       ...            ...        ...  
1455       0      8    2007        WD         Normal     175000  
1456       0      2    2010        WD         Normal     210000  
1457    2500      5    2010        WD         Normal     266500  
1458       0      4    2010        WD         Normal     142125  
1459       0      6    2008        WD         Normal     147500  

[1460 rows x 80 columns]

## Question 14

In [18]:
#Drop Column PoolQC
hp_df.drop(['PoolQC'],axis=1,inplace=True)
hp_df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  \
0        1          60       RL         65.0     8450   Pave      Reg   
1        2          20       RL         80.0     9600   Pave      Reg   
2        3          60       RL         68.0    11250   Pave      IR1   
3        4          70       RL         60.0     9550   Pave      IR1   
4        5          60       RL         84.0    14260   Pave      IR1   
...    ...         ...      ...          ...      ...    ...      ...   
1455  1456          60       RL         62.0     7917   Pave      Reg   
1456  1457          20       RL         85.0    13175   Pave      Reg   
1457  1458          70       RL         66.0     9042   Pave      Reg   
1458  1459          20       RL         68.0     9717   Pave      Reg   
1459  1460          20       RL         75.0     9937   Pave      Reg   

     LandContour Utilities LotConfig  ... ScreenPorch PoolArea  Fence  \
0            Lvl    AllPub    Inside  ...           0        0    NaN   
1            Lvl    AllPub       FR2  ...           0        0    NaN   
2            Lvl    AllPub    Inside  ...           0        0    NaN   
3            Lvl    AllPub    Corner  ...           0        0    NaN   
4            Lvl    AllPub       FR2  ...           0        0    NaN   
...          ...       ...       ...  ...         ...      ...    ...   
1455         Lvl    AllPub    Inside  ...           0        0    NaN   
1456         Lvl    AllPub    Inside  ...           0        0  MnPrv   
1457         Lvl    AllPub    Inside  ...           0        0  GdPrv   
1458         Lvl    AllPub    Inside  ...           0        0    NaN   
1459         Lvl    AllPub    Inside  ...           0        0    NaN   

     MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0            NaN       0      2    2008        WD         Normal     208500  
1            NaN       0      5    2007        WD         Normal     181500  
2            NaN       0      9    2008        WD         Normal     223500  
3            NaN       0      2    2006        WD        Abnorml     140000  
4            NaN       0     12    2008        WD         Normal     250000  
...          ...     ...    ...     ...       ...            ...        ...  
1455         NaN       0      8    2007        WD         Normal     175000  
1456         NaN       0      2    2010        WD         Normal     210000  
1457        Shed    2500      5    2010        WD         Normal     266500  
1458         NaN       0      4    2010        WD         Normal     142125  
1459         NaN       0      6    2008        WD         Normal     147500  

[1460 rows x 79 columns]

## Question 15

In [76]:
#Drop all rows that have missing values in either BsmtFinType2 or BsmtQual
hp_df.dropna(subset=['BsmtFinType2', 'BsmtQual'])

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
Id                                                                            
1             60       RL         65.0     8450   Pave      Reg         Lvl   
2             20       RL         80.0     9600   Pave      Reg         Lvl   
3             60       RL         68.0    11250   Pave      IR1         Lvl   
4             70       RL         60.0     9550   Pave      IR1         Lvl   
5             60       RL         84.0    14260   Pave      IR1         Lvl   
...          ...      ...          ...      ...    ...      ...         ...   
1456          60       RL         62.0     7917   Pave      Reg         Lvl   
1457          20       RL         85.0    13175   Pave      Reg         Lvl   
1458          70       RL         66.0     9042   Pave      Reg         Lvl   
1459          20       RL         68.0     9717   Pave      Reg         Lvl   
1460          20       RL         75.0     9937   Pave      Reg         Lvl   

     Utilities LotConfig LandSlope  ... ScreenPorch PoolArea  Fence  \
Id                                  ...                               
1       AllPub    Inside       Gtl  ...           0        0    NaN   
2       AllPub       FR2       Gtl  ...           0        0    NaN   
3       AllPub    Inside       Gtl  ...           0        0    NaN   
4       AllPub    Corner       Gtl  ...           0        0    NaN   
5       AllPub       FR2       Gtl  ...           0        0    NaN   
...        ...       ...       ...  ...         ...      ...    ...   
1456    AllPub    Inside       Gtl  ...           0        0    NaN   
1457    AllPub    Inside       Gtl  ...           0        0  MnPrv   
1458    AllPub    Inside       Gtl  ...           0        0  GdPrv   
1459    AllPub    Inside       Gtl  ...           0        0    NaN   
1460    AllPub    Inside       Gtl  ...           0        0    NaN   

     MiscFeature MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
Id                                                                           
1            NaN       0       2    2008        WD         Normal    208500  
2            NaN       0       5    2007        WD         Normal    181500  
3            NaN       0       9    2008        WD         Normal    223500  
4            NaN       0       2    2006        WD        Abnorml    140000  
5            NaN       0      12    2008        WD         Normal    250000  
...          ...     ...     ...     ...       ...            ...       ...  
1456         NaN       0       8    2007        WD         Normal    175000  
1457         NaN       0       2    2010        WD         Normal    210000  
1458        Shed    2500       5    2010        WD         Normal    266500  
1459         NaN       0       4    2010        WD         Normal    142125  
1460         NaN       0       6    2008        WD         Normal    147500  

[1422 rows x 78 columns]

In [78]:
hp_df['BsmtQual'].isnull()

Id
1       False
2       False
3       False
4       False
5       False
        ...  
1456    False
1457    False
1458    False
1459    False
1460    False
Name: BsmtQual, Length: 1460, dtype: bool

## Question 16

In [79]:
hp_df['LotFrontage'].mean()

70.04995836802642

In [80]:
## Fill in the missing values in LotFrontage with the Mean of LotFrontage
hp_df['LotFrontage'].fillna(hp_df['LotFrontage'].mean(),inplace=True) 
hp_df.head(20)

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
Id                                                                          
1           60       RL    65.000000     8450   Pave      Reg         Lvl   
2           20       RL    80.000000     9600   Pave      Reg         Lvl   
3           60       RL    68.000000    11250   Pave      IR1         Lvl   
4           70       RL    60.000000     9550   Pave      IR1         Lvl   
5           60       RL    84.000000    14260   Pave      IR1         Lvl   
6           50       RL    85.000000    14115   Pave      IR1         Lvl   
7           20       RL    75.000000    10084   Pave      Reg         Lvl   
8           60       RL    70.049958    10382   Pave      IR1         Lvl   
9           50       RM    51.000000     6120   Pave      Reg         Lvl   
10         190       RL    50.000000     7420   Pave      Reg         Lvl   
11          20       RL    70.000000    11200   Pave      Reg         Lvl   
12          60       RL    85.000000    11924   Pave      IR1         Lvl   
13          20       RL    70.049958    12968   Pave      IR2         Lvl   
14          20       RL    91.000000    10652   Pave      IR1         Lvl   
15          20       RL    70.049958    10920   Pave      IR1         Lvl   
16          45       RM    51.000000     6120   Pave      Reg         Lvl   
17          20       RL    70.049958    11241   Pave      IR1         Lvl   
18          90       RL    72.000000    10791   Pave      Reg         Lvl   
19          20       RL    66.000000    13695   Pave      Reg         Lvl   
20          20       RL    70.000000     7560   Pave      Reg         Lvl   

   Utilities LotConfig LandSlope  ... ScreenPorch PoolArea  Fence MiscFeature  \
Id                                ...                                           
1     AllPub    Inside       Gtl  ...           0        0    NaN         NaN   
2     AllPub       FR2       Gtl  ...           0        0    NaN         NaN   
3     AllPub    Inside       Gtl  ...           0        0    NaN         NaN   
4     AllPub    Corner       Gtl  ...           0        0    NaN         NaN   
5     AllPub       FR2       Gtl  ...           0        0    NaN         NaN   
6     AllPub    Inside       Gtl  ...           0        0  MnPrv        Shed   
7     AllPub    Inside       Gtl  ...           0        0    NaN         NaN   
8     AllPub    Corner       Gtl  ...           0        0    NaN        Shed   
9     AllPub    Inside       Gtl  ...           0        0    NaN         NaN   
10    AllPub    Corner       Gtl  ...           0        0    NaN         NaN   
11    AllPub    Inside       Gtl  ...           0        0    NaN         NaN   
12    AllPub    Inside       Gtl  ...           0        0    NaN         NaN   
13    AllPub    Inside       Gtl  ...         176        0    NaN         NaN   
14    AllPub    Inside       Gtl  ...           0        0    NaN         NaN   
15    AllPub    Corner       Gtl  ...           0        0   GdWo         NaN   
16    AllPub    Corner       Gtl  ...           0        0  GdPrv         NaN   
17    AllPub   CulDSac       Gtl  ...           0        0    NaN        Shed   
18    AllPub    Inside       Gtl  ...           0        0    NaN        Shed   
19    AllPub    Inside       Gtl  ...           0        0    NaN         NaN   
20    AllPub    Inside       Gtl  ...           0        0  MnPrv         NaN   

   MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
Id                                                             
1        0       2    2008        WD         Normal    208500  
2        0       5    2007        WD         Normal    181500  
3        0       9    2008        WD         Normal    223500  
4        0       2    2006        WD        Abnorml    140000  
5        0      12    2008        WD         Normal    250000  
6      700      10    2009        WD         Normal    143000  
7        0    

## Question 17

In [82]:
#7. Create a New column LotAreaMetres which will be The value of LotArea inSquare Metres. (1 square foot = 0.092903Square Metres)
hp_df['LotArea sqm'] = df['LotArea'] *  0.092903
hp_df

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
Id                                                                            
1             60       RL         65.0     8450   Pave      Reg         Lvl   
2             20       RL         80.0     9600   Pave      Reg         Lvl   
3             60       RL         68.0    11250   Pave      IR1         Lvl   
4             70       RL         60.0     9550   Pave      IR1         Lvl   
5             60       RL         84.0    14260   Pave      IR1         Lvl   
...          ...      ...          ...      ...    ...      ...         ...   
1456          60       RL         62.0     7917   Pave      Reg         Lvl   
1457          20       RL         85.0    13175   Pave      Reg         Lvl   
1458          70       RL         66.0     9042   Pave      Reg         Lvl   
1459          20       RL         68.0     9717   Pave      Reg         Lvl   
1460          20       RL         75.0     9937   Pave      Reg         Lvl   

     Utilities LotConfig LandSlope  ... PoolArea  Fence MiscFeature MiscVal  \
Id                                  ...                                       
1       AllPub    Inside       Gtl  ...        0    NaN         NaN       0   
2       AllPub       FR2       Gtl  ...        0    NaN         NaN       0   
3       AllPub    Inside       Gtl  ...        0    NaN         NaN       0   
4       AllPub    Corner       Gtl  ...        0    NaN         NaN       0   
5       AllPub       FR2       Gtl  ...        0    NaN         NaN       0   
...        ...       ...       ...  ...      ...    ...         ...     ...   
1456    AllPub    Inside       Gtl  ...        0    NaN         NaN       0   
1457    AllPub    Inside       Gtl  ...        0  MnPrv         NaN       0   
1458    AllPub    Inside       Gtl  ...        0  GdPrv        Shed    2500   
1459    AllPub    Inside       Gtl  ...        0    NaN         NaN       0   
1460    AllPub    Inside       Gtl  ...        0    NaN         NaN       0   

     MoSold  YrSold  SaleType  SaleCondition  SalePrice  LotArea sqm  
Id                                                                    
1         2    2008        WD         Normal     208500   891.868800  
2         5    2007        WD         Normal     181500  1045.158750  
3         9    2008        WD         Normal     223500   887.223650  
4         2    2006        WD        Abnorml     140000  1324.796780  
5        12    2008        WD         Normal     250000  1311.325845  
...     ...     ...       ...            ...        ...          ...  
1456      8    2007        WD         Normal     175000  1223.997025  
1457      2    2010        WD         Normal     210000   840.028926  
1458      5    2010        WD         Normal     266500   902.738451  
1459      4    2010        WD         Normal     142125   923.177111  
1460      6    2008        WD         Normal     147500          NaN  

[1460 rows x 79 columns]

## Question 18


In [51]:
#Set the Id column as the new index
hp_df.set_index("Id",inplace=True)

In [52]:
hp_df.head(5)

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
Id                                                                          
1           60       RL         65.0     8450   Pave      Reg         Lvl   
2           20       RL         80.0     9600   Pave      Reg         Lvl   
3           60       RL         68.0    11250   Pave      IR1         Lvl   
4           70       RL         60.0     9550   Pave      IR1         Lvl   
5           60       RL         84.0    14260   Pave      IR1         Lvl   

   Utilities LotConfig LandSlope  ... ScreenPorch PoolArea Fence MiscFeature  \
Id                                ...                                          
1     AllPub    Inside       Gtl  ...           0        0   NaN         NaN   
2     AllPub       FR2       Gtl  ...           0        0   NaN         NaN   
3     AllPub    Inside       Gtl  ...           0        0   NaN         NaN   
4     AllPub    Corner       Gtl  ...           0        0   NaN         NaN   
5     AllPub       FR2       Gtl  ...           0        0   NaN         NaN   

   MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
Id                                                             
1        0       2    2008        WD         Normal    208500  
2        0       5    2007        WD         Normal    181500  
3        0       9    2008        WD         Normal    223500  
4        0       2    2006        WD        Abnorml    140000  
5        0      12    2008        WD         Normal    250000  

[5 rows x 78 columns]

## Question 19
using loc and Iloc,
● Return a dataframe with rows at index 6, 54 and 70
● Return a dataframe with rows from index 50 onwards
● Return a dataframe with rows at index 50 to index 100 and columns MSSubClass, LotFrontage,LotArea and SalePrice
● Return a dataframe with all rows and columns SalePrice, and SaleCondition


In [53]:
#Return a dataframe with rows at index 6, 54 and 70
#iloc
hp_df.iloc[[5,53,69],:]



MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
Id                                                                          
6           50       RL         85.0    14115   Pave      IR1         Lvl   
54          20       RL         68.0    50271   Pave      IR1         Low   
70          50       RL         81.0    15593   Pave      Reg         Lvl   

   Utilities LotConfig LandSlope  ... ScreenPorch PoolArea  Fence MiscFeature  \
Id                                ...                                           
6     AllPub    Inside       Gtl  ...           0        0  MnPrv        Shed   
54    AllPub    Inside       Gtl  ...           0        0    NaN         NaN   
70    AllPub    Corner       Gtl  ...           0        0    NaN         NaN   

   MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
Id                                                             
6      700      10    2009        WD         Normal    143000  
54       0      11    2006        WD         Normal    385000  
70       0       7    2006        WD         Normal    225000  

[3 rows x 78 columns]

In [54]:
#Return a dataframe with rows at index 6, 54 and 70
hp_df.loc[[6,54,70],:]

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
Id                                                                          
6           50       RL         85.0    14115   Pave      IR1         Lvl   
54          20       RL         68.0    50271   Pave      IR1         Low   
70          50       RL         81.0    15593   Pave      Reg         Lvl   

   Utilities LotConfig LandSlope  ... ScreenPorch PoolArea  Fence MiscFeature  \
Id                                ...                                           
6     AllPub    Inside       Gtl  ...           0        0  MnPrv        Shed   
54    AllPub    Inside       Gtl  ...           0        0    NaN         NaN   
70    AllPub    Corner       Gtl  ...           0        0    NaN         NaN   

   MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
Id                                                             
6      700      10    2009        WD         Normal    143000  
54       0      11    2006        WD         Normal    385000  
70       0       7    2006        WD         Normal    225000  

[3 rows x 78 columns]

In [55]:
#Return a dataframe with rows from index 50 onwards
hp_df.iloc[49:]

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
Id                                                                            
50            20       RL    66.000000     7742   Pave      Reg         Lvl   
51            60       RL    70.049958    13869   Pave      IR2         Lvl   
52            50       RM    52.000000     6240   Pave      Reg         Lvl   
53            90       RM   110.000000     8472   Grvl      IR2         Bnk   
54            20       RL    68.000000    50271   Pave      IR1         Low   
...          ...      ...          ...      ...    ...      ...         ...   
1456          60       RL    62.000000     7917   Pave      Reg         Lvl   
1457          20       RL    85.000000    13175   Pave      Reg         Lvl   
1458          70       RL    66.000000     9042   Pave      Reg         Lvl   
1459          20       RL    68.000000     9717   Pave      Reg         Lvl   
1460          20       RL    75.000000     9937   Pave      Reg         Lvl   

     Utilities LotConfig LandSlope  ... ScreenPorch PoolArea  Fence  \
Id                                  ...                               
50      AllPub    Inside       Gtl  ...           0        0  MnPrv   
51      AllPub    Corner       Gtl  ...           0        0    NaN   
52      AllPub    Inside       Gtl  ...           0        0  MnPrv   
53      AllPub    Corner       Mod  ...           0        0    NaN   
54      AllPub    Inside       Gtl  ...           0        0    NaN   
...        ...       ...       ...  ...         ...      ...    ...   
1456    AllPub    Inside       Gtl  ...           0        0    NaN   
1457    AllPub    Inside       Gtl  ...           0        0  MnPrv   
1458    AllPub    Inside       Gtl  ...           0        0  GdPrv   
1459    AllPub    Inside       Gtl  ...           0        0    NaN   
1460    AllPub    Inside       Gtl  ...           0        0    NaN   

     MiscFeature MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
Id                                                                           
50           NaN       0       1    2007        WD         Normal    127000  
51           NaN       0       7    2007        WD         Normal    177000  
52          Shed     400       9    2006        WD         Normal    114500  
53           NaN       0       5    2010        WD         Normal    110000  
54           NaN       0      11    2006        WD         Normal    385000  
...          ...     ...     ...     ...       ...            ...       ...  
1456         NaN       0       8    2007        WD         Normal    175000  
1457         NaN       0       2    2010        WD         Normal    210000  
1458        Shed    2500       5    2010        WD         Normal    266500  
1459         NaN       0       4    2010        WD         Normal    142125  
1460         NaN       0       6    2008        WD         Normal    147500  

[1411 rows x 78 columns]

In [56]:
hp_df.loc[50:]

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
Id                                                                            
50            20       RL    66.000000     7742   Pave      Reg         Lvl   
51            60       RL    70.049958    13869   Pave      IR2         Lvl   
52            50       RM    52.000000     6240   Pave      Reg         Lvl   
53            90       RM   110.000000     8472   Grvl      IR2         Bnk   
54            20       RL    68.000000    50271   Pave      IR1         Low   
...          ...      ...          ...      ...    ...      ...         ...   
1456          60       RL    62.000000     7917   Pave      Reg         Lvl   
1457          20       RL    85.000000    13175   Pave      Reg         Lvl   
1458          70       RL    66.000000     9042   Pave      Reg         Lvl   
1459          20       RL    68.000000     9717   Pave      Reg         Lvl   
1460          20       RL    75.000000     9937   Pave      Reg         Lvl   

     Utilities LotConfig LandSlope  ... ScreenPorch PoolArea  Fence  \
Id                                  ...                               
50      AllPub    Inside       Gtl  ...           0        0  MnPrv   
51      AllPub    Corner       Gtl  ...           0        0    NaN   
52      AllPub    Inside       Gtl  ...           0        0  MnPrv   
53      AllPub    Corner       Mod  ...           0        0    NaN   
54      AllPub    Inside       Gtl  ...           0        0    NaN   
...        ...       ...       ...  ...         ...      ...    ...   
1456    AllPub    Inside       Gtl  ...           0        0    NaN   
1457    AllPub    Inside       Gtl  ...           0        0  MnPrv   
1458    AllPub    Inside       Gtl  ...           0        0  GdPrv   
1459    AllPub    Inside       Gtl  ...           0        0    NaN   
1460    AllPub    Inside       Gtl  ...           0        0    NaN   

     MiscFeature MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
Id                                                                           
50           NaN       0       1    2007        WD         Normal    127000  
51           NaN       0       7    2007        WD         Normal    177000  
52          Shed     400       9    2006        WD         Normal    114500  
53           NaN       0       5    2010        WD         Normal    110000  
54           NaN       0      11    2006        WD         Normal    385000  
...          ...     ...     ...     ...       ...            ...       ...  
1456         NaN       0       8    2007        WD         Normal    175000  
1457         NaN       0       2    2010        WD         Normal    210000  
1458        Shed    2500       5    2010        WD         Normal    266500  
1459         NaN       0       4    2010        WD         Normal    142125  
1460         NaN       0       6    2008        WD         Normal    147500  

[1411 rows x 78 columns]

In [57]:
#Return a dataframe with rows at index 50 to index 100 and columns MSSubClass, LotFrontage,LotArea and SalePrice
hp_df.iloc[49:100,[0,2,3,77]]

MSSubClass  LotFrontage  LotArea  SalePrice
Id                                              
50           20    66.000000     7742     127000
51           60    70.049958    13869     177000
52           50    52.000000     6240     114500
53           90   110.000000     8472     110000
54           20    68.000000    50271     385000
55           80    60.000000     7134     130000
56           20   100.000000    10175     180500
57          160    24.000000     2645     172500
58           60    89.000000    11645     196500
59           60    66.000000    13682     438780
60           20    60.000000     7200     124900
61           20    63.000000    13072     158000
62           75    60.000000     7200     101000
63          120    44.000000     6442     202500
64           70    50.000000    10300     140000
65           60    70.049958     9375     219500
66           60    76.000000     9591     317000
67           20    70.049958    19900     180000
68           20    72.000000    10665     226000
69           30    47.000000     4608      80000
70           50    81.000000    15593     225000
71           20    95.000000    13651     244000
72           20    69.000000     7599     129500
73           60    74.000000    10141     185000
74           20    85.000000    10200     144900
75           50    60.000000     5790     107400
76          180    21.000000     1596      91000
77           20    70.049958     8475     135750
78           50    50.000000     8635     127000
79           90    72.000000    10778     136500
80           50    60.000000    10440     110000
81           60   100.000000    13000     193500
82          120    32.000000     4500     153500
83           20    78.000000    10206     245000
84           20    80.000000     8892     126500
85           80    70.049958     8530     168500
86           60   121.000000    16059     260000
87           60   122.000000    11911     174000
88          160    40.000000     3951     164500
89           50   105.000000     8470      85000
90           20    60.000000     8070     123600
91           20    60.000000     7200     109900
92           20    85.000000     8500      98600
93           30    80.000000    13360     163500
94          190    60.000000     7200     133900
95           60    69.000000     9337     204750
96           60    70.049958     9765     185000
97           20    78.000000    10264     214000
98           20    73.000000    10921      94750
99           30    85.000000    10625      83000
100          20    77.000000     9320     128950

In [58]:
#Return a dataframe with rows at index 50 to index 100 and columns MSSubClass, LotFrontage,LotArea and SalePrice
hp_df.loc[50:100,['MSSubClass','LotFrontage','LotArea','SalePrice']]

MSSubClass  LotFrontage  LotArea  SalePrice
Id                                              
50           20    66.000000     7742     127000
51           60    70.049958    13869     177000
52           50    52.000000     6240     114500
53           90   110.000000     8472     110000
54           20    68.000000    50271     385000
55           80    60.000000     7134     130000
56           20   100.000000    10175     180500
57          160    24.000000     2645     172500
58           60    89.000000    11645     196500
59           60    66.000000    13682     438780
60           20    60.000000     7200     124900
61           20    63.000000    13072     158000
62           75    60.000000     7200     101000
63          120    44.000000     6442     202500
64           70    50.000000    10300     140000
65           60    70.049958     9375     219500
66           60    76.000000     9591     317000
67           20    70.049958    19900     180000
68           20    72.000000    10665     226000
69           30    47.000000     4608      80000
70           50    81.000000    15593     225000
71           20    95.000000    13651     244000
72           20    69.000000     7599     129500
73           60    74.000000    10141     185000
74           20    85.000000    10200     144900
75           50    60.000000     5790     107400
76          180    21.000000     1596      91000
77           20    70.049958     8475     135750
78           50    50.000000     8635     127000
79           90    72.000000    10778     136500
80           50    60.000000    10440     110000
81           60   100.000000    13000     193500
82          120    32.000000     4500     153500
83           20    78.000000    10206     245000
84           20    80.000000     8892     126500
85           80    70.049958     8530     168500
86           60   121.000000    16059     260000
87           60   122.000000    11911     174000
88          160    40.000000     3951     164500
89           50   105.000000     8470      85000
90           20    60.000000     8070     123600
91           20    60.000000     7200     109900
92           20    85.000000     8500      98600
93           30    80.000000    13360     163500
94          190    60.000000     7200     133900
95           60    69.000000     9337     204750
96           60    70.049958     9765     185000
97           20    78.000000    10264     214000
98           20    73.000000    10921      94750
99           30    85.000000    10625      83000
100          20    77.000000     9320     128950

In [59]:
# Return a dataframe with all rows and columns SalePrice, and SaleCondition
hp_df.iloc[:,[76,77]]

SaleCondition  SalePrice
Id                           
1           Normal     208500
2           Normal     181500
3           Normal     223500
4          Abnorml     140000
5           Normal     250000
...            ...        ...
1456        Normal     175000
1457        Normal     210000
1458        Normal     266500
1459        Normal     142125
1460        Normal     147500

[1460 rows x 2 columns]

In [60]:
# Return a dataframe with all rows and columns SalePrice, and SaleCondition
hp_df.loc[:,['SalePrice','SaleCondition']]

SalePrice SaleCondition
Id                           
1        208500        Normal
2        181500        Normal
3        223500        Normal
4        140000       Abnorml
5        250000        Normal
...         ...           ...
1456     175000        Normal
1457     210000        Normal
1458     266500        Normal
1459     142125        Normal
1460     147500        Normal

[1460 rows x 2 columns]

## Question 20

In [47]:
#Use corr() function to find the correlation among the columns in the dataframe using ‘Pearson’ method.
hp_df.corr(method ='pearson') 


Id  MSSubClass  LotFrontage   LotArea  OverallQual  \
Id             1.000000    0.011156    -0.010601 -0.033226    -0.028365   
MSSubClass     0.011156    1.000000    -0.386347 -0.139781     0.032628   
LotFrontage   -0.010601   -0.386347     1.000000  0.426095     0.251646   
LotArea       -0.033226   -0.139781     0.426095  1.000000     0.105806   
OverallQual   -0.028365    0.032628     0.251646  0.105806     1.000000   
OverallCond    0.012609   -0.059316    -0.059213 -0.005636    -0.091932   
YearBuilt     -0.012713    0.027850     0.123349  0.014228     0.572323   
YearRemodAdd  -0.021998    0.040581     0.088866  0.013788     0.550684   
MasVnrArea    -0.050298    0.022936     0.193458  0.104160     0.411876   
BsmtFinSF1    -0.005024   -0.069836     0.233633  0.214103     0.239666   
BsmtFinSF2    -0.005968   -0.065649     0.049900  0.111170    -0.059119   
BsmtUnfSF     -0.007940   -0.140759     0.132644 -0.002618     0.308159   
TotalBsmtSF   -0.015415   -0.238518     0.392075  0.260833     0.537808   
1stFlrSF       0.010496   -0.251758     0.457181  0.299475     0.476224   
2ndFlrSF       0.005590    0.307886     0.080177  0.050986     0.295493   
LowQualFinSF  -0.044230    0.046474     0.038469  0.004779    -0.030429   
GrLivArea      0.008273    0.074853     0.402797  0.263116     0.593007   
BsmtFullBath   0.002289    0.003491     0.100949  0.158155     0.111098   
BsmtHalfBath  -0.020155   -0.002333    -0.007234  0.048046    -0.040150   
FullBath       0.005587    0.131608     0.198769  0.126031     0.550600   
HalfBath       0.006784    0.177354     0.053532  0.014259     0.273458   
BedroomAbvGr   0.037719   -0.023438     0.263170  0.119690     0.101676   
KitchenAbvGr   0.002951    0.281721    -0.006069 -0.017784    -0.183882   
TotRmsAbvGrd   0.027239    0.040380     0.352096  0.190015     0.427452   
Fireplaces    -0.019772   -0.045569     0.266639  0.271364     0.396765   
GarageYrBlt    0.000072    0.085072     0.070250 -0.024947     0.547766   
GarageCars     0.016570   -0.040110     0.285691  0.154871     0.600671   
GarageArea     0.017634   -0.098672     0.344997  0.180403     0.562022   
WoodDeckSF    -0.029643   -0.012579     0.088521  0.171698     0.238923   
OpenPorchSF   -0.000477   -0.006100     0.151972  0.084774     0.308819   
EnclosedPorch  0.002889   -0.012037     0.010700 -0.018340    -0.113937   
3SsnPorch     -0.046635   -0.043825     0.070029  0.020423     0.030371   
ScreenPorch    0.001330   -0.026030     0.041383  0.043160     0.064886   
PoolArea       0.057044    0.008283     0.206167  0.077672     0.065166   
MiscVal       -0.006242   -0.007683     0.003368  0.038068    -0.031406   
MoSold         0.021172   -0.013585     0.011200  0.001205     0.070815   
YrSold         0.000712   -0.021407     0.007450 -0.014261    -0.027347   
SalePrice     -0.021917   -0.084284     0.351799  0.263843     0.790982   

               OverallCond  YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1  \
Id                0.012609  -0.012713     -0.021998   -0.050298   -0.005024   
MSSubClass       -0.059316   0.027850      0.040581    0.022936   -0.069836   
LotFrontage      -0.059213   0.123349      0.088866    0.193458    0.233633   
LotArea          -0.005636   0.014228      0.013788    0.104160    0.214103   
OverallQual      -0.091932   0.572323      0.550684    0.411876    0.239666   
OverallCond       1.000000  -0.375983      0.073741   -0.128101   -0.046231   
YearBuilt        -0.375983   1.000000      0.592855    0.315707    0.249503   
YearRemodAdd      0.073741   0.592855      1.000000    0.179618    0.128451   
MasVnrArea       -0.128101   0.315707      0.179618    1.000000    0.264736   
BsmtFinSF1       -0.046231   0.249503      0.128451    0.264736    1.000000   
BsmtFinSF2        0.040229  -0.049107     -0.067759   -0.072319   -0.050117   
BsmtUnfSF        -0.136841   0.149040      0.181133    0.114442   -0.495251   
TotalBsmtSF      -0.171098   0.391452      0.291066    0.363936    0

## Question 21

In [46]:
#Use corr() function to find the correlation among the columns in the dataframe using ‘kendall’ method.
hp_df.corr(method ='kendall') 

Id  MSSubClass  LotFrontage   LotArea  OverallQual  \
Id             1.000000    0.014198    -0.022489 -0.003550    -0.020898   
MSSubClass     0.014198    1.000000    -0.236067 -0.200790     0.083506   
LotFrontage   -0.022489   -0.236067     1.000000  0.510666     0.193309   
LotArea       -0.003550   -0.200790     0.510666  1.000000     0.173136   
OverallQual   -0.020898    0.083506     0.193309  0.173136     1.000000   
OverallCond    0.002698   -0.057833    -0.065029 -0.036164    -0.152513   
YearBuilt     -0.004035    0.010922     0.138978  0.074436     0.505804   
YearRemodAdd  -0.008415   -0.003649     0.083595  0.053329     0.437687   
MasVnrArea    -0.026222    0.018061     0.197848  0.132267     0.341051   
BsmtFinSF1    -0.009105   -0.079554     0.112092  0.120827     0.104062   
BsmtFinSF2    -0.005545   -0.071900     0.042690  0.057501    -0.101893   
BsmtUnfSF     -0.006501   -0.086258     0.082474  0.052923     0.205094   
TotalBsmtSF   -0.022232   -0.234613     0.274099  0.252669     0.349043   
1stFlrSF      -0.000301   -0.201798     0.306016  0.311072     0.307490   
2ndFlrSF       0.006823    0.405345     0.042451  0.086576     0.244571   
LowQualFinSF  -0.023080    0.066860    -0.024931 -0.016481    -0.030355   
GrLivArea      0.002175    0.141142     0.261243  0.304676     0.464189   
BsmtFullBath   0.003751   -0.037486     0.070795  0.077897     0.087385   
BsmtHalfBath  -0.017531    0.002230    -0.003209  0.037564    -0.045162   
FullBath       0.005745    0.169025     0.180774  0.190968     0.513944   
HalfBath       0.002064    0.250498     0.079747  0.116139     0.265575   
BedroomAbvGr   0.032048    0.064922     0.259606  0.267224     0.104216   
KitchenAbvGr   0.006189    0.244957     0.001819 -0.018601    -0.171960   
TotRmsAbvGrd   0.018760    0.133565     0.277150  0.303366     0.351349   
Fireplaces    -0.010813    0.016988     0.198863  0.279682     0.365010   
GarageYrBlt   -0.000457    0.052619     0.081254  0.030517     0.474646   
GarageCars     0.009987    0.019290     0.278278  0.264666     0.543120   
GarageArea     0.004082   -0.035341     0.263120  0.247904     0.424225   
WoodDeckSF    -0.031211    0.018110     0.080382  0.133455     0.209439   
OpenPorchSF   -0.002009    0.025413     0.129485  0.126485     0.346309   
EnclosedPorch -0.005360    0.010590    -0.075647 -0.051719    -0.139530   
3SsnPorch     -0.029802   -0.031583     0.052914  0.050724     0.029395   
ScreenPorch    0.004762   -0.018751     0.035484  0.074070     0.040856   
PoolArea       0.045303    0.029447     0.069963  0.068907     0.050609   
MiscVal       -0.035251   -0.028830     0.019833  0.048161    -0.078040   
MoSold         0.013966    0.014059     0.018147  0.004481     0.047233   
YrSold         0.001326   -0.021802     0.002403 -0.020255    -0.020327   
SalePrice     -0.012030   -0.003979     0.290361  0.314174     0.669660   

               OverallCond  YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1  \
Id                0.002698  -0.004035     -0.008415   -0.026222   -0.009105   
MSSubClass       -0.057833   0.010922     -0.003649    0.018061   -0.079554   
LotFrontage      -0.065029   0.138978      0.083595    0.197848    0.112092   
LotArea          -0.036164   0.074436      0.053329    0.132267    0.120827   
OverallQual      -0.152513   0.505804      0.437687    0.341051    0.104062   
OverallCond       1.000000  -0.329379     -0.031641   -0.149822   -0.012308   
YearBuilt        -0.329379   1.000000      0.624893    0.300645    0.151742   
YearRemodAdd     -0.031641   0.624893      1.000000    0.176332    0.051501   
MasVnrArea       -0.149822   0.300645      0.176332    1.000000    0.187837   
BsmtFinSF1       -0.012308   0.151742      0.051501    0.187837    1.000000   
BsmtFinSF2        0.092477  -0.090010     -0.101920   -0.053776    0.036774   
BsmtUnfSF        -0.096586   0.087547      0.120251    0.056767   -0.412606   
TotalBsmtSF      -0.168321   0.296103      0.208188    0.272309    0

## Question 22

In [45]:
#What is the highest sale Price in the dataset?
hp_df['SalePrice'].max()

755000

## Question 23

In [44]:
#Return a dataframe with information on the most expensive house in the dataset.

hp_df.loc[hp_df['SalePrice'].idxmax(),]

Id                  692
MSSubClass           60
MSZoning             RL
LotFrontage         104
LotArea           21535
                  ...  
MoSold                1
YrSold             2007
SaleType             WD
SaleCondition    Normal
SalePrice        755000
Name: 691, Length: 79, dtype: object

## Question 24

In [43]:
#Return a dataframe with only houses whose price is higher than 500000
hp_df.loc[hp_df['SalePrice']>500000]

Id  MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  \
178    179          20       RL         63.0    17423   Pave      IR1   
440    441          20       RL        105.0    15431   Pave      Reg   
691    692          60       RL        104.0    21535   Pave      IR1   
769    770          60       RL         47.0    53504   Pave      IR2   
803    804          60       RL        107.0    13891   Pave      Reg   
898    899          20       RL        100.0    12919   Pave      IR1   
1046  1047          60       RL         85.0    16056   Pave      IR1   
1169  1170          60       RL        118.0    35760   Pave      IR1   
1182  1183          60       RL        160.0    15623   Pave      IR1   

     LandContour Utilities LotConfig  ... ScreenPorch PoolArea  Fence  \
178          Lvl    AllPub   CulDSac  ...           0        0    NaN   
440          Lvl    AllPub    Inside  ...         170        0    NaN   
691          Lvl    AllPub    Corner  ...           0        0    NaN   
769          HLS    AllPub   CulDSac  ...         210        0    NaN   
803          Lvl    AllPub    Inside  ...         192        0    NaN   
898          Lvl    AllPub    Inside  ...           0        0    NaN   
1046         Lvl    AllPub    Inside  ...           0        0    NaN   
1169         Lvl    AllPub   CulDSac  ...           0        0    NaN   
1182         Lvl    AllPub    Corner  ...           0      555  MnPrv   

     MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
178          NaN       0      7    2009       New        Partial     501837  
440          NaN       0      4    2009        WD         Normal     555000  
691          NaN       0      1    2007        WD         Normal     755000  
769          NaN       0      6    2010        WD         Normal     538000  
803          NaN       0      1    2009       New        Partial     582933  
898          NaN       0      3    2010       New        Partial     611657  
1046         NaN       0      7    2006       New        Partial     556581  
1169         NaN       0      7    2006        WD         Normal     625000  
1182         NaN       0      7    2007        WD        Abnorml     745000  

[9 rows x 79 columns]

## Question 25

In [42]:
#What is the Mean Price of a house according to its SaleCondition?
mean=hp_df['SalePrice'].mean()
mean

180921.19589041095

## Question 26

In [88]:
#What is the average price for houses built before 2010?
yearbuilt=hp_df.loc[hp_df['YearBuilt']<2010]
yearbuilt['SalePrice'].mean()

180774.85538039752

## Question 27
Create two dataframes using the dictionaries below then merge them using inner,outer,right, left join
Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995,135925 , 71400]}
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower':[141, 80, 182 , 160]}


In [21]:
Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995,135925 , 71400]}
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower':[141, 80, 182 , 160]}

#convert the dictionary into  a dataframe

carp=pd.DataFrame(Car_Price)
carh=pd.DataFrame(car_Horsepower)


In [36]:
#inner join
innerjoin = pd.merge(carp, carh, how='inner')
innerjoin

Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160

In [38]:
leftjoin=pd.merge(carp,carh, how='left')
leftjoin

Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160

In [94]:
rightjoin=pd.merge(carp,carh, on='Company', how='right' )

rightjoin

Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160

In [96]:
#outer join
outerjoin=pd.merge(carp,carh, on='Company', how='outer')
outerjoin

Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160

## Question 28

Create two data frames using the dictionaries below, Concatenate those two
dataframes and create a key for each data frame
Hint syntax for concat : new_dataframe = pd.concat([dataframe1,
dataframe2], keys=['key1', 'key2'])
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845,171995, 135925 , 71400]}
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price':[29995, 23600, 61500 58900]}


In [41]:
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845,171995, 135925 , 71400]}
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price':[29995, 23600, 61500 ,58900]}

gc=pd.DataFrame(GermanCars)
jc=pd.DataFrame(japaneseCars)

pd.concat([gc,jc], keys=['key1', 'key2'])

Company   Price
key1 0         Ford   23845
     1     Mercedes  171995
     2          BMV  135925
     3         Audi   71400
key2 0       Toyota   29995
     1        Honda   23600
     2       Nissan   61500
     3  Mitsubishi    58900